INSERT INTO pokemon(name) VALUES
('Bulbasaur'),
('Ivysaur'),
('Venusaur'),
('Charmander'),
('Charmeleon'),
('Charizard'),
('Squirtle'),
('Wartortle'),
('Blastoise'),
('Caterpie'),
('Metapod'),
('Butterfree'),
('Weedle'),
('Kakuna'),
('Beedrill'),
('Pidgey'),
('Pidgeotto'),
('Pidgeot'),
('Rattata'),
('Raticate'),
('Spearow'),
('Fearow'),
('Ekans'),
('Arbok'),
('Pikachu'),
('Raichu'),
('Sandshrew'),
('Sandslash'),
('Nidoran♀'),
('Nidorina'),
('Nidoqueen'),
('Nidoran♂'),
('Nidorino'),
('Nidoking'),
('Clefairy'),
('Clefable'),
('Vulpix'),
('Ninetales'),
('Jigglypuff'),
('Wigglytuff'),
('Zubat'),
('Golbat'),
('Oddish'),
('Gloom'),
('Vileplume'),
('Paras'),
('Parasect'),
('Venonat'),
('Venomoth'),
('Diglett'),
('Dugtrio'),
('Meowth'),
('Persian'),
('Psyduck'),
('Golduck'),
('Mankey'),
('Primeape'),
('Growlithe'),
('Arcanine'),
('Poliwag'),
('Poliwhirl'),
('Poliwrath'),
('Abra'),
('Kadabra'),
('Alakazam'),
('Machop'),
('Machoke'),
('Machamp'),
('Bellsprout'),
('Weepinbell'),
('Victreebel'),
('Tentacool'),
('Tentacruel'),
('Geodude'),
('Graveler'),
('Golem'),
('Ponyta'),
('Rapidash'),
('Slowpoke'),
('Slowbro'),
('Magnemite'),
('Magneton'),
('Farfetchd'),
('Doduo'),
('Dodrio'),
('Seel'),
('Dewgong'),
('Grimer'),
('Muk'),
('Shellder'),
('Cloyster'),
('Gastly'),
('Haunter'),
('Gengar'),
('Onix'),
('Drowzee'),
('Hypno'),
('Krabby'),
('Kingler'),
('Voltorb'),
('Electrode'),
('Exeggcute'),
('Exeggutor'),
('Cubone'),
('Marowak'),
('Hitmonlee'),
('Hitmonchan'),
('Lickitung'),
('Koffing'),
('Weezing'),
('Rhyhorn'),
('Rhydon'),
('Chansey'),
('Tangela'),
('Kangaskhan'),
('Horsea'),
('Seadra'),
('Goldeen'),
('Seaking'),
('Staryu'),
('Starmie'),
('Mr. Mime'),
('Scyther'),
('Jynx'),
('Electabuzz'),
('Magmar'),
('Pinsir'),
('Tauros'),
('Magikarp'),
('Gyarados'),
('Lapras'),
('Ditto'),
('Eevee'),
('Vaporeon'),
('Jolteon'),
('Flareon'),
('Porygon'),
('Omanyte'),
('Omastar'),
('Kabuto'),
('Kabutops'),
('Aerodactyl'),
('Snorlax'),
('Articuno'),
('Zapdos'),
('Moltres'),
('Dratini'),
('Dragonair'),
('Dragonite'),
('Mewtwo'),
('Mew');

UPDATE pokemon SET caught = TRUE WHERE name = 'Charmander';


CREATE TABLE pokemon
( poke_id   SERIAL      PRIMARY KEY
, name      VARCHAR(30) NOT NULL
, seen      BOOLEAN     
, caught    BOOLEAN);

CREATE TABLE image
( img_id    SERIAL      PRIMARY KEY
, img_name  VARCHAR(100)    NOT NULL
, img_path  VARCHAR(150)    NOT NULL
, poke_id   INT             NOT NULL REFERENCES pokemon(poke_id));



